apiVersion: v1
kind: Service
metadata:
  name: auto-content-gen-service
  namespace: {{ .Values.namespace }}
  labels:
    app: auto-content-gen
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
  selector:
    app: auto-content-gen
