apiVersion: v1
kind: Service
metadata:
  name: adminserver-service
  namespace: {{ .Values.namespace }}
  labels:
    app: adminserver
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 5513
      targetPort: 5513
      protocol: TCP   
  selector:
    app: adminserver
