apiVersion: v1
kind: Service
metadata:
  name: apiserver-service
  namespace: {{ .Values.namespace }}
  labels:
    app: apiserver
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: websocket
      port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: apiserver
