# Default values for memeenvy.

namespace: memeenvy

image:
  repository: ghcr.io/deeplearningintelligence/prod-memeenvy-adminserver
  pullPolicy: IfNotPresent
  tag: "1.0.1"

imagePullSecrets:
  - name: ghcr-login-secret

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
