# Default values for memeenvy.

namespace: memeenvy

image:
  repository: ghcr.io/deeplearningintelligence/auto-content-gen
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ghcr-login-secret

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
